a, b = 4,3
p = int(input("enter the value of p "))
g = int(input("enter the value of g "))

print(f'secret key of a is {a} and b is {b}')

xa = (g**a)%p
xb= (g**b)%p

print(f'secret key of a generated intermediate is {xa} which is sent to b')
print(f'secret key of b generated intermediate is {xb} which is sent to a')

Ka = (xb**a)%p
Kb = (xa**b)%p

print(f' the final keys generated by a and b are {Ka} and {Kb}')
